# <Modulating Image Restoration with Continual Levels via Adaptive Feature Modification Layers>
# With 16 Residual blocks w/o adafm

#### general settings
name: 001_basicmodel_bicx3_scratch_DIV2K # 001_adafmnet_bicx4_finetune_DIV2K | 001_basicmodel_bicx3_scratch_DIV2K
use_tb_logger: true
model: sr
distortion: sr
scale: 1
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: DIV2K
    mode: LQGT
    dataroot_GT: ../datasets/DIV2K/DIV2K800_sub.lmdb
    dataroot_LQ: ../datasets/DIV2K/DIV2K800_sub_bicx4.lmdb

    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 16
    GT_size: 96 # crop size
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: val_set5
    mode: LQGT
    dataroot_GT: ../datasets/val_set5/Set5
    dataroot_LQ: ../datasets/val_set5/Set5_bicx4

#### network structures
network_G:
  which_model_G: AdaFMNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 16
  adafm_ksize: 1 # None(~) for basic model; 1 | 3 | 5 | 7 for AdaFM-Net

#### path
path:
  pretrain_model_G: ~ # None(~) for basic model; path of basic model for adafm training
  strict_load: false
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1: 0.9
  beta2: 0.99
  lr_scheme: MultiStepLR

  niter: 1000000
  warmup_iter: -1  # no warm up
  lr_steps: [500000]  # [500000] for basic model, [1000000] for adafm-net
  lr_gamma: 0.1

  finetune_adafm: true # false for basic model; true for adafm training

  pixel_criterion: l1
  pixel_weight: 1.0

  manual_seed: 0
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 100
